parameters:
  - name: page
    in: query
    description: The page number to retrieve
    required: false
    schema:
      type: integer
      minimum: 1
      default: 1
  - name: size
    in: query
    description: The number of items per page
    required: false
    schema:
      type: integer
      minimum: 1
      maximum: 100
      default: 20